Server:
  port: 8085
spring:
  application:
    name: clientezabud
  profiles:
    active: local

---
spring:
  profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/cliente
    username: postgres
    password: 1234
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest


  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: none
